In [37]:
import os
from time import localtime
import pandas as pd
from operator import itemgetter
def readfile(directory):
    # A list of stored files and when they were modified
    files_with_mtime = []
    # Iterate through all the files in the directory
    for filename in os.listdir(directory):
        # Construct the complete file path
        file_path = os.path.join(directory, filename)
        # Make sure it's a file and not a directory
        if os.path.isfile(file_path):
            # Gets the modification time of the file
            modification_time = os.path.getmtime(file_path)
            # 将时间戳转换为本地时间
            local_time = localtime(modification_time)
            # Add the file name and converted local time to the list
            files_with_mtime.append((filename, local_time))
    # Filter out the CSV file and sort it by modification time
    csv_files_sorted = sorted(files_with_mtime, key=itemgetter(1))
    # Store a list of read DataFrames
    dataframes = []
    # Traverse the sorted CSV file
    for filename, mtime in csv_files_sorted:
        # Construct the complete file path
        file_path = os.path.join(directory, filename)
        # Read the CSV file
        df = pd.read_csv(file_path)
        # Add the read DataFrame to the list
        dataframes.append((df, mtime))
        # Prints the read file name and the time when it was modified
        print(f"The file has been read：{filename}, Modify time：{mtime}")
        # If required, the read data can be further processed
        # For example, merge all DataFrames
        combined_df = pd.concat([df for df, _ in dataframes], ignore_index=True)
    return combined_df

In [38]:
def process(combined_df):
    df_cleaned = combined_df.applymap(lambda x: x.replace("tensor(", "").replace(")", "") if isinstance(x, str) else x)
    return df_cleaned
def str_to_float(x):
    # Check if x is a string, and if so, try to convert to floating-point
    if isinstance(x, str):
        try:
            return float(x)
        except ValueError:
            return x  # If the conversion fails, the original value is returned
    return x


In [39]:
# Specify the directory path
directory = './save2/alltrain-c/'
combined_df = readfile(directory)
df_cleaned = process(combined_df)
all_train_c = df_cleaned.applymap(str_to_float)

已读取文件：15_20_57.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=20, tm_sec=57, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_20_58.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=20, tm_sec=58, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_20_59.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=21, tm_sec=0, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_21_1.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=21, tm_sec=1, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_21_2.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=21, tm_sec=2, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_21_4.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=21, tm_sec=4, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_21_5.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=21, tm_sec=5, tm_wday=6

已读取文件：15_22_16.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=22, tm_sec=17, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_22_18.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=22, tm_sec=18, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_22_19.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=22, tm_sec=20, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_22_21.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=22, tm_sec=21, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_22_22.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=22, tm_sec=22, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_22_23.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=22, tm_sec=24, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_22_25.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=22, tm_sec=25, 

已读取文件：15_23_36.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=23, tm_sec=36, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_23_37.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=23, tm_sec=38, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_23_39.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=23, tm_sec=39, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_23_40.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=23, tm_sec=40, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_23_41.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=23, tm_sec=42, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_23_43.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=23, tm_sec=43, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_23_44.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=23, tm_sec=45, 

已读取文件：15_24_57.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=24, tm_sec=57, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_24_58.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=24, tm_sec=58, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_24_59.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=25, tm_sec=0, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_25_1.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=25, tm_sec=1, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_25_2.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=25, tm_sec=2, tm_wday=6, tm_yday=182, tm_isdst=0)


In [40]:
# Specify the directory path
directory = './save2/alltrain-n/'
combined_df = readfile(directory)
df_cleaned = process(combined_df)
all_train_n = df_cleaned.applymap(str_to_float)

已读取文件：15_29_50.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=29, tm_sec=51, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_29_52.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=29, tm_sec=52, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_29_53.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=29, tm_sec=53, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_29_54.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=29, tm_sec=55, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_29_56.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=29, tm_sec=56, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_29_57.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=29, tm_sec=57, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_29_59.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=29, tm_sec=59, 

已读取文件：15_31_8.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=31, tm_sec=8, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_31_9.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=31, tm_sec=9, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_31_10.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=31, tm_sec=11, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_31_12.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=31, tm_sec=12, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_31_13.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=31, tm_sec=14, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_31_15.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=31, tm_sec=15, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_31_16.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=31, tm_sec=16, tm_w

已读取文件：15_32_27.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=32, tm_sec=27, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_32_29.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=32, tm_sec=29, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_32_30.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=32, tm_sec=30, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_32_31.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=32, tm_sec=32, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_32_33.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=32, tm_sec=33, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_32_34.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=32, tm_sec=35, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_32_36.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=32, tm_sec=36, 

已读取文件：15_33_46.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=33, tm_sec=46, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_33_47.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=33, tm_sec=47, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_33_48.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=33, tm_sec=49, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_33_50.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=33, tm_sec=50, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_33_51.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=33, tm_sec=51, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_33_52.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=33, tm_sec=53, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_33_54.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=33, tm_sec=54, 

In [41]:
# Specify the directory path
directory = './save2/allval-c/'
combined_df = readfile(directory)
df_cleaned = process(combined_df)
all_val_c = df_cleaned.applymap(str_to_float)

已读取文件：15_27_46.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=27, tm_sec=46, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_27_48.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=27, tm_sec=48, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_27_49.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=27, tm_sec=49, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_27_50.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=27, tm_sec=50, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_27_52.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=27, tm_sec=52, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_27_53.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=27, tm_sec=53, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_27_55.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=27, tm_sec=55, 

In [42]:
# Specify the directory path
directory = './save2/allval-n'
combined_df = readfile(directory)
df_cleaned = process(combined_df)
all_val_n = df_cleaned.applymap(str_to_float)

已读取文件：15_35_21.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=35, tm_sec=21, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_35_22.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=35, tm_sec=23, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_35_24.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=35, tm_sec=24, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_35_25.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=35, tm_sec=25, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_35_26.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=35, tm_sec=27, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_35_28.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=35, tm_sec=28, tm_wday=6, tm_yday=182, tm_isdst=0)
已读取文件：15_35_29.csv, 修改时间：time.struct_time(tm_year=2024, tm_mon=6, tm_mday=30, tm_hour=15, tm_min=35, tm_sec=29, 

In [43]:
all_train_c.shape

(177, 2048)

In [44]:
all_train_c *= 1.2
all_train_n *= 1
train = pd.concat([all_train_c, all_train_n], axis=1)

In [45]:
all_val_c *= 1.2
all_val_n *= 1
val = pd.concat([all_val_c, all_val_n], axis=1)

In [46]:
# Specify the directory path and file name
import pandas as pd
# Specify the path to .txt file
file_path = './video_data/train_all.txt'
# Determine the separator (e.g., comma ',', tab 't', space '', etc.)
# The delimiter is assumed to be a tab
delimiter = ' '
Y_train = pd.read_csv(file_path, delimiter=delimiter, header=None)
file_path = './video_data/val_all.txt'
# Determine the separator (e.g., comma ',', tab 't', space '', etc.)
# The delimiter is assumed to be a tab
delimiter = ' '
Y_val = pd.read_csv(file_path, delimiter=delimiter, header=None)

In [47]:
Y_train = Y_train.iloc[:, -1]
Y_val = Y_val.iloc[:, -1]

In [48]:
Y_train

0      2
1      2
2      1
3      1
4      1
      ..
172    2
173    2
174    0
175    2
176    1
Name: 1, Length: 177, dtype: int64

In [49]:
Y_val

0     0
1     0
2     1
3     1
4     1
5     2
6     1
7     1
8     1
9     2
10    2
11    0
12    2
13    0
14    1
15    2
16    1
17    1
18    2
19    1
20    2
21    1
22    1
23    1
24    1
25    0
26    1
27    2
28    1
29    2
30    1
31    1
32    0
33    0
34    2
35    1
36    2
37    0
38    2
39    2
40    1
41    1
42    0
43    2
44    2
Name: 1, dtype: int64

In [50]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Initialize the random forest model
# n_estimators is the number of trees in the forest, and max_depth is the maximum depth of the trees
rf = RandomForestClassifier(n_estimators=300, max_depth=10)

# Train the model
rf.fit(train, Y_train)

# Predict the test set
y_pred = rf.predict(val)

# Evaluate the model
accuracy = accuracy_score(Y_val, y_pred)
print(f"Model accuracy: {accuracy}")

模型准确率: 0.6888888888888889


In [51]:
from sklearn.metrics import classification_report
import numpy as np
print(classification_report(Y_val, y_pred))

              precision    recall  f1-score   support

           0       0.64      1.00      0.78         9
           1       0.85      0.52      0.65        21
           2       0.61      0.73      0.67        15

    accuracy                           0.69        45
   macro avg       0.70      0.75      0.70        45
weighted avg       0.73      0.69      0.68        45



In [52]:
Y_val.values

array([0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 1, 2, 1, 2, 1,
       1, 1, 1, 0, 1, 2, 1, 2, 1, 1, 0, 0, 2, 1, 2, 0, 2, 2, 1, 1, 0, 2,
       2], dtype=int64)

In [53]:
y_pred

array([0, 0, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 1,
       0, 1, 2, 0, 2, 2, 1, 2, 2, 2, 0, 0, 2, 1, 2, 0, 2, 0, 1, 0, 0, 2,
       1], dtype=int64)

In [54]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import ElasticNet

# Define the model
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100),
    'SVM': SVC(probability=True, random_state=20),
    'Logistic Regression': LogisticRegression(max_iter=200),
    'MLP': MLPClassifier(max_iter=100),
    #'Elastic Net': ElasticNet()
}

# Evaluate the model and print the results
for name, model in models.items():
    # Train the model
    model.fit(train, Y_train)
    
    # Predict the test set
    y_pred = model.predict(val)
    
    # Calculate the accuracy
    accuracy = accuracy_score(Y_val, y_pred)
    print(f"{name} accuracy: {accuracy:.2f}")

Random Forest 的准确率: 0.64
SVM 的准确率: 0.69


C:\Users\15281\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression 的准确率: 0.69
MLP 的准确率: 0.64


In [55]:
rf = MLPClassifier(max_iter=100)

# Train the model
rf.fit(train, Y_train)

# Predict the test set
y_pred = rf.predict(val)

# Evaluate the model
accuracy = accuracy_score(Y_val, y_pred)
print(f"Model accuracy: {accuracy}")

模型准确率: 0.7111111111111111


C:\Users\15281\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


In [56]:
from sklearn.metrics import classification_report
import numpy as np
print(classification_report(Y_val, y_pred))

              precision    recall  f1-score   support

           0       0.60      1.00      0.75         9
           1       0.86      0.57      0.69        21
           2       0.69      0.73      0.71        15

    accuracy                           0.71        45
   macro avg       0.71      0.77      0.72        45
weighted avg       0.75      0.71      0.71        45



In [35]:
Y_val.values

array([0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 1, 2, 1, 2, 1,
       1, 1, 1, 0, 1, 2, 1, 2, 1, 1, 0, 0, 2, 1, 2, 0, 2, 2, 1, 1, 0, 2,
       2], dtype=int64)

In [36]:
y_pred

array([0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 1,
       1, 1, 2, 0, 1, 2, 1, 2, 2, 2, 0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 2,
       2], dtype=int64)